### ISSUE TITLE
Cannot install after upgrading to high sierra

### ISSUE THREAD

**Issue by zrob** [simonleung8/cli-plugin-recorder#4]
$ cf install-plugin CLI-Recorder
Searching CF-Community for plugin CLI-Recorder...
Plugin CLI-Recorder 1.0.2 found in: CF-Community
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Do you want to install the plugin CLI-Recorder? [yN]: y
Starting download of plugin binary from repository CF-Community...
 7.70 MiB / 7.70 MiB [============================================================================================================================] 100.00% 1s
failed MSpanList_Insert 0x620000 0xb7d82448739 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x56130b)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/panic.go:491 +0xad fp=0x7ffeefbfae10 sp=0x7ffeefbfade0
runtime.MSpanList_Insert(0x58a7a8, 0x620000)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:692 +0x8f fp=0x7ffeefbfae38 sp=0x7ffeefbfae10
MHeap_FreeSpanLocked(0x5873a0, 0x620000, 0x100)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:583 +0x163 fp=0x7ffeefbfae78 sp=0x7ffeefbfae38
MHeap_Grow(0x5873a0, 0x8, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:420 +0x1a8 fp=0x7ffeefbfaeb8 sp=0x7ffeefbfae78
MHeap_AllocSpanLocked(0x5873a0, 0x1, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:298 +0x365 fp=0x7ffeefbfaef8 sp=0x7ffeefbfaeb8
mheap_alloc(0x5873a0, 0x1, 0x12, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:190 +0x121 fp=0x7ffeefbfaf20 sp=0x7ffeefbfaef8
runtime.MHeap_Alloc(0x5873a0, 0x1, 0x10000000012, 0xf149)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:240 +0x66 fp=0x7ffeefbfaf58 sp=0x7ffeefbfaf20
MCentral_Grow(0x58f118, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mcentral.c:197 +0x8b fp=0x7ffeefbfafc0 sp=0x7ffeefbfaf58
runtime.MCentral_CacheSpan(0x58f118, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mcentral.c:85 +0x167 fp=0x7ffeefbfaff8 sp=0x7ffeefbfafc0
runtime.MCache_Refill(0x61c000, 0x12, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mcache.c:90 +0xa0 fp=0x7ffeefbfb020 sp=0x7ffeefbfaff8
runtime.mcacheRefill_m()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/malloc.c:368 +0x57 fp=0x7ffeefbfb040 sp=0x7ffeefbfb020
runtime.onM(0x4539d8)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:273 +0x9a fp=0x7ffeefbfb048 sp=0x7ffeefbfb040
runtime.mallocgc(0x120, 0x380120, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/malloc.go:178 +0x849 fp=0x7ffeefbfb0f8 sp=0x7ffeefbfb048
runtime.newobject(0x380120, 0x61c000)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/malloc.go:353 +0x49 fp=0x7ffeefbfb120 sp=0x7ffeefbfb0f8
runtime.newG(0x2894a)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.go:233 +0x2a fp=0x7ffeefbfb138 sp=0x7ffeefbfb120
allocg(0x577800)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.c:925 +0x1f fp=0x7ffeefbfb148 sp=0x7ffeefbfb138
runtime.malg(0x8000, 0x577c40)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.c:2106 +0x1f fp=0x7ffeefbfb178 sp=0x7ffeefbfb148
runtime.mpreinit(0x578260)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/os_darwin.c:137 +0x27 fp=0x7ffeefbfb190 sp=0x7ffeefbfb178
mcommoninit(0x578260)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.c:201 +0xc9 fp=0x7ffeefbfb1b8 sp=0x7ffeefbfb190
runtime.schedinit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.c:138 +0x55 fp=0x7ffeefbfb1e0 sp=0x7ffeefbfb1b8
runtime.rt0_go(0x7ffeefbfb218, 0x3, 0x7ffeefbfb218, 0x0, 0x0, 0x3, 0x7ffeefbfb500, 0x7ffeefbfb533, 0x7ffeefbfb539, 0x0, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:95 +0x116 fp=0x7ffeefbfb1e8 sp=0x7ffeefbfb1e0
exit status 2
File is not a valid cf CLI plugin binary.

**Comment by simonleung8** [comment]
Should be resolved now.
